sudo: required
services:
 - docker

before_install: gem install bundler --pre
 - docker build -t arcdev1/docker-react -f Dockerfile.dev .

script:
 - docker run arcdev1/docker-react npm run test -- --coverage
