language: node_js
node_js:
  - '8'
sudo: required
services:
 - docker

before_install:
 - docker build -t arcdev1/docker-react -f Dockerfile.dev .

script:
 - docker run arcdev1/docker-react npm run test -- --coverage
