sudo: required
services:
- docker


before_install: gem install bundler --pre
- docker build -t arcxda/docker-react -f Dockerfile.dev .

script:
- docker run arcxda/docker-react npm run test -- --coverage
